---
cog_bundle_version: 4
name: rundeck
description: "Rundeck interface via go-rundeck"
author: "Stephen Price <stephen@stp5.net>"
homepage: "https://github.com/steeef/cog-go-rundeck"
version: "0.3.0"
long_description: |
  A wrapper for [go-rundeck](https://github.com/lusis/go-rundeck).
config:
  notes: |
    In order to authenticate against Rundeck, you must either use
    `RUNDECK_USERNAME` and `RUNDECK_PASSWORD`, or `RUNDECK_TOKEN`.
  env:
    - var: RUNDECK_URL
      description: |
        **Required**. The full URL to your Rundeck instance
        (e.g., `http://rundeck.example:4440`).
    - var: RUNDECK_TOKEN
      description: |
        The API token to use.
    - var: RUNDECK_USERNAME
    - var: RUNDECK_PASSWORD
    - var: RUNDECK_DEFAULT_PROJECT
      description: |
        Optional. The default Rundeck project to use if not specified with `--prj`
        in commands.
permissions:
  - rundeck:read
  - rundeck:run
docker:
  image: "steeef/cog-go-rundeck"
  tag: "latest"
commands:
  list:
    executable: exec "/bundle/cog-go-rundeck" "list-jobs"
    description: "List available jobs."
    examples: |
      rundeck:list --prj myproject
    long_description: |
      List jobs in a project. If "--prj" is not specified, use the default.
    rules:
      - "must have rundeck:read"
    options:
      prj:
        description: "Project ID of jobs to list."
        type: string
        required: false
        short_flag: p
  run:
    executable: exec "/bundle/cog-go-rundeck" "run-job"
    description: "Run a job by name."
    long_description: |
      Run a specific job by its name. If "--prj" is not specified, use the default.
    examples: |
      rundeck:run --prj myproject myjob
      rundeck:run --prj myproject --args "some arguments" myjob
      rundeck:run myjob
    rules:
      - "must have rundeck:run"
    arguments: "<jobname>"
    options:
      prj:
        description: "Project ID of jobs to list."
        type: string
        required: false
        short_flag: p
      args:
        description: "Arguments to send to the job."
        type: string
        required: false
        short_flag: a
templates:
  joblist:
    body: |
      ~each var=$results~
      ~each var=$item.Jobs as=j~
      **~$j.Name~**: ~$j.Description~
      ~end~
      ~end~